### ISSUE TITLE
Frontend folder is empty

### ISSUE THREAD

**Issue by tsdtsdtsd** [create-go-app/cli#81]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): `Linux abc 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux`
- Golang (`go version`): `go1.16.4`
- Create Go App CLI (`cgapp -v`): `2.1.1`

**Describe the bug:**

After creating a project, the `frontend` folder is empty.
Output from create command:

```
❯ cgapp create

Create a new project via Create Go App CLI v2.1.1...

[?] Choose a backend framework: fiber
[?] Choose a frontend framework/library: vue
[?] Choose a web/proxy server: nginx
[?] If everything is okay, can I create this project for you? ;) Yes

[OK] Backend was created with template `fiber`!
[OK] Frontend was created with template `vue`!
[OK] Web/Proxy server configuration for `nginx` was created!
[OK] Ansible inventory, playbook and roles for deploying was created!

[INFO] Completed in 2 seconds!

* Please put credentials into the Ansible inventory file (`hosts.ini`) before you start deploying a project!
* Visit https://vitejs.dev/guide/ for more info about using the `vue` frontend template!
* A helpful documentation and next steps with your project is here https://create-go.app/

Have a happy new project! :)
```

**Steps to reproduce the behavior:**

1. `cgapp create`
2. Choose `fiber`
3. Choose `vue`
4. Choose `nginx`
5. Choose `Yes`

**Expected behavior:**

Something existing in `frontend` folder.

**Comment by tsdtsdtsd** [comment]
Added output from `tree` command:
[tree.txt](https://github.com/create-go-app/cli/files/6491858/tree.txt)

**Comment by koddr** [comment]
@tsdtsdtsd hi!

This issue was totally described at our Wiki page [here](https://github.com/create-go-app/cli/wiki/Errors-in-the-process#in-creating-the-project). 
Quick answer is just update your local `npm` (to `v7.x`) or use Docker-way to create a new project.

**Comment by byouloh** [comment]
For beginners, why don't you inform "npm 7.x higher for the frondend" in the README file.

**Comment by koddr** [comment]
@byouloh hi!

First, you are also free to open a PR with this edit to the README file of this repository if you notice any missing or unclear points in the project description! 😉 

> For beginners, why don't you inform "npm 7.x higher for the frondend" in the README file.

Because it was described in the project [Wiki](https://github.com/create-go-app/cli/wiki/Errors-in-the-process#in-creating-the-project), and I've never seen a system with Go `1.16` (the minimum recommended building the CLI from source) but very old npm `6.x`... 🤷

Also, according to my observations, it is more common for CLI to use the [Docker-way](https://github.com/create-go-app/cli#-docker-way-to-quick-start) to create a new project. Let me remind you that if you use it, you **don't need** to think about the versioning of your npm because it is already there (with the right version) in our Docker image.

Ok, I'll add the tip about this to the README, no problem!
